import { StyleSheet } from "react-native";

export const commonStyles = StyleSheet.create({
  errorText: {
    color: 'red',
    textAlign: 'center',
    marginTop: 20,
    fontSize: 14,
    flex: 1,
  },
  noResultText: {
    textAlign: 'center',
    marginTop: 20,
    color: '#6c757d',
  },
  resultCountContainer: {
    alignItems: 'flex-end',
    marginBottom: 10,
    marginRight: 5,
  },
  resultCountText: {
    fontSize: 14,
    color: '#6c757d',
  },
  markerStatusText: {
    fontSize: 12,
    color: '#868e96',
    marginTop: 2,
  },
  tabHeader: {
    flexDirection: 'row',
    marginHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  activeTabButton: {
    backgroundColor: '#F8FAFE',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  tabButtonText: {
    marginLeft: 6,
    fontSize: 16,
    fontWeight: '500',
  },
  activeTabButtonText: {
    color: '#3690FF',
    fontWeight: '600',
  },
  searchTabContent: {
    flex: 1,
    paddingVertical: 20,
  },
  routeTabContent: {
    flex: 1,
  },
  routeTabScrollContent: {
    paddingVertical: 20,
    paddingBottom: 30,
    flexGrow: 1,
  },
  transportModeWrapper: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
  },
  transportModeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: -10,
    paddingHorizontal: 16,
    width: '100%',
  },
  transportModeButtonDisabled: {
    backgroundColor: '#f5f5f5',
    borderColor: '#e0e0e0',
    opacity: 0.6,
  },
  routeInputsContainer: {
    marginBottom: 16,
  },
  routeInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: 'rgba(248, 250, 254, 0.9)',
    borderWidth: 1,
    borderColor: '#B9B9B9',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  routeInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeTextInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    paddingVertical: 6,
    minHeight: 6,
  },
  searchIndicator: {
    position: 'absolute',
    right: 8,
    top: 4,
  },
  routeInputClearButton: {
    position: 'absolute',
    right: 8,
    top: 4,
  },
  currentLocationButton: {
    padding: 4,
    marginLeft: 8,
  },
  currentLocationButtonDisabled: {
    opacity: 0.6,
  },
  swapButton: {
    padding: 4,
    marginLeft: 8,
  },
  routeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#007bff',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 0,
    marginBottom: 16,
  },
  routeButtonDisabled: {
    backgroundColor: '#6c757d',
    opacity: 0.6,
  },
  routeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  searchResultsList: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dee2e6',
    borderRadius: 8,
    marginBottom: 12,
    marginTop: 8,
    paddingVertical: 8,
    maxHeight: 180,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchResultsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f3f4',
  },
  searchResultsScrollContainer: {
    maxHeight: 160,
  },
  noResultsContainer: {
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    margin: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
    borderStyle: 'dashed',
  },
  noResultsText: {
    fontSize: 14,
    color: '#6c757d',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f3f4',
    backgroundColor: '#fff',
  },
  searchResultContent: {
    flex: 1,
  },
  searchResultTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginBottom: 2,
  },
  searchResultAddress: {
    fontSize: 12,
    color: '#666',
  },
  departButton: {
    backgroundColor: '#007bff',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
    marginLeft: 8,
    minWidth: 50,
    alignItems: 'center',
  },
  departButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  errorContainer: {
    backgroundColor: '#f8d7da',
    borderColor: '#f5c6cb',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  errorCloseButton: {
    padding: 4,
    marginLeft: 8,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: 65,
    left: 0,
    right: 0,
    zIndex: 9999,
    backgroundColor: 'white',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  suggestionsList: {
    maxHeight: 205, // Adjusted to fit 5 items + title without scrolling (approx 25px per item + 26px for title)
  },
  suggestionItem: {
    paddingVertical: 5, // Further reduced vertical padding
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  suggestionsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    paddingVertical: 6, // Further adjusted vertical padding
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  removeRecentSearchButton: {
    padding: 5,
  },
  closeButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 1,
  },
  subTabContainer: {
    flexDirection: 'row',
    marginTop: 16,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  subTabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeSubTabButton: {
    borderBottomColor: '#3690FF',
  },
  subTabButtonText: {
    fontSize: 16,
    color: '#B9B9B9',
  },
  activeSubTabButtonText: {
    color: '#3690FF',
    fontWeight: 'bold',
  },
  tabContent: {
    flex: 1,
  },
  parkingLotContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  parkingLotText: {
    fontSize: 16,
    color: '#B9B9B9',
  },
});
